Refactor out DefaultFormatter (#35)
apache/accumulo-examples pull request #56
Opened 2019-07-08 14:31 UTC by lbschanno

Refactor out usage of DefaultFormatter. It is an internal-only unstable
API that is not recommended for users, and as such is unsuitable to
include in examples.

2019-07-08 17:51 UTC, milleruntime requested changes
@lbschanno thanks for the contribution!  I just have a couple things for your changes...

I think copying the code from DefaultFormatter is fine but the two new methods should be placed in a Util class to be reused across the examples.  Right now you have duplicate code, which we try to avoid.

2019-07-08 17:51 UTC, milleruntime commented on src/main/java/org/apache/accumulo/examples/filedata/ChunkInputFormat.java
> +        System.out.println("nextKeyValue called");
Should use the logger here.

2019-07-08 19:00 UTC, lbschanno commented
@milleruntime No problem. Please take a look at the update for the requested changes and let me know if anything else needs to be modified.

2019-07-09 16:00 UTC, milleruntime commented
Looks good!  

With recent changes to Accumulo Master migrating to Java 11, the example repo is broken.  I will work on getting it up to date and then merge your PR.

2019-07-09 16:18 UTC, lbschanno commented
Thanks, much appreciated!

2019-07-09 16:55 UTC, milleruntime approved these changes

2019-07-09 16:55 UTC, merged